include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    unnecessary_this: false
    use_build_context_synchronously: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    prefer_is_empty: false
    always_use_package_imports: true
