include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    unnecessary_this: false
    use_build_context_synchronously: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    prefer_is_empty: false
    always_use_package_imports: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    # prefer_final_locals: true
    prefer_final_parameters: true
    prefer_double_quotes: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_lambdas: true
    unnecessary_null_checks: true
    unnecessary_parenthesis: true
    use_enums: true
    use_named_constants: true
    always_put_required_named_parameters_first: true
    one_member_abstracts: true
