name: loure
description: A Nostr client.
publish_to: 'none'

version: 2.0.0+15

environment:
  sdk: ^3.3.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # nostr: ^1.3.4
  pointycastle: ^3.7.4
  encrypt: ^5.0.3
  convert: ^3.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  bot_toast: ^4.1.3
  flutter_quill: ^9.3.1
  # nostr_dart: ^0.6.5
  bip340: ^0.2.0
  string_validator: ^1.0.2
  http: ^1.2.1
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5
  sqflite_common: ^2.4.5
  sqflite_common_ffi_web: ^0.3.6
  get_time_ago: ^1.2.2
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.2.19
  flutter_animate: ^4.1.1+1
  bech32: ^0.2.2
  hex: ^0.2.0
  wechat_assets_picker: ^8.8.1+1
  file_picker: ^6.1.1
  dio: ^5.1.2
  dio_cookie_manager: ^3.0.0
  emoji_picker_flutter: ^1.6.3
  widget_size: ^1.0.0
  # webview_flutter: ^4.4.2
  flutter_inappwebview: ^6.0.0
  screenshot: ^2.1.0
  share_plus: ^7.2.1
  video_player: ^2.8.2
  image_picker: ^1.0.7
  # keframe: ^3.0.0
  pretty_qr_code: ^2.0.3
  flutter_link_previewer: ^3.2.2
  easy_image_viewer: ^1.4.1
  android_intent_plus: ^4.0.1
  flutter_placeholder_textlines: ^1.2.0
  google_fonts: 5.1.0
  flutter_font_picker: ^1.3.0
  local_auth: ^2.1.7
  flutter_socks_proxy: ^0.0.3
  crypto: ^3.0.3
  mime: ^1.0.4
  pretty_dio_logger: ^1.3.1
  google_mlkit_translation: ^0.9.0
  google_mlkit_language_id: ^0.9.0
  flutter_markdown: ^0.6.20+1
  window_manager: ^0.3.4
  qr_code_scanner: ^1.0.1
  web_socket_channel: ^2.4.0
  image_gallery_saver: ^1.7.1
  permission_handler: ^10.2.0
  file_saver: ^0.2.9
  auto_size_text_field: ^2.2.1
  numberpicker: ^2.1.2
  table_calendar: ^3.0.9
  intl: ^0.18.1
  device_info_plus: ^9.1.0
  flutter_cache_manager: ^3.3.1
  clock: ^1.1.1
  graphql_data_loader2: ^6.0.0
  path: ^1.9.0
  path_provider: ^2.1.2
  flutter_chat_types: ^3.6.2
  markdown: ^7.2.2
  http_parser: ^4.0.2
  flutter_secure_storage: ^9.0.0
  collection: ^1.18.0
  url_launcher: ^6.2.5
  fleather: ^1.14.4
  parchment_delta: ^1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  photo_manager: ^3.0.0-dev.5
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

dependency_overrides:
  extended_image: ^8.1.1
  markdown: ^7.1.0
  intl: ^0.18.1
  win32: ^5.0.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/imgs/
    - assets/imgs/logo/logo512.png
    # - assets/imgs/logo/logo_android.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# new version icons
flutter_launcher_icons:
  image_path_ios: 'assets/imgs/logo/logo_ios.jpg'
  image_path_android: 'assets/imgs/logo/logo_android.png'
  android: true
  ios: true
  windows:
    generate: true
    image_path: "assets/imgs/logo/logo_android.png"
  macos:
    generate: true
    image_path: "assets/imgs/logo/logo_ios.jpg"

flutter_native_splash:
  color: "#f6f3f3"
  image: assets/imgs/logo/logo512.png
  fullscreen: true
